config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'homes_about'
  resources :users, only: [:new, :index, :show, :edit, :create, :update]
  resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { in: 1..200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: {minimum:2, in: 2..20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image (width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about,:sign_up,:log_in ]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resouces)
      user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit]
  def new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book2 = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if
      @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if
      @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private
  def book_params
    params.require( :book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]
  def new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if
      @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
  <h2>User info</h2>
    <table class="table">
      <tbody>
        <tr>
          <%= image_tag user.get_profile_image(63, 63) %>
        </tr>
        <tr>
	       <th>name</th>
	       <th><%= user.name %></th>
        </tr>
        <tr>
	       <th>introduction</th>
	       <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
      <div class="row">
        <%= link_to edit_user_path(user.id), class:'btn btn-outline-secondary btn-block' do %>
         <span class="fas fa-user-cog"></span>
        <% end %>
      </div>
    <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title,"Title" %><br>
          <%= f.text_field :title ,class: 'form-control book_title'%>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %><br>
          <%= f.text_area :body ,class: 'form-control book_body'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book' ,class: 'btn btn-success'%>
        </div>
      <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div class="text-danger">
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= @book.errors.count %>errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      </div>
    	<%= form_with model: @book, local: true do |f| %>
          <div class="form-group">
            <label for="input Name">Title</label><br>
           <%= f.text_field :title, autofocus: true, id:"book_title", class:'form-control title' %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Opinion</label><br>
            <%= f.text_area :body, autofocus: true, id:"book_body", class: 'form-control body' %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book", class:'btn btn-success' %>
          </div>
        <% end %>
        <%= link_to "Show" ,book_path(@book) %>
        |
        <%= link_to "Back" ,books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="text-danger">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </div>
  <div class="row">
    <%= render 'books/book', book: @book, user: current_user, type: :reset %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(40, 40)%>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book', book: @book2, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
            <%= link_to user_path(@user) do%>
              <%= image_tag @book.user.get_profile_image(40,40)%><br><%= @book.user.name %>
            <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to 'Edit',edit_book_path(@book), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to 'Destroy',book_path(@book), method: :delete, class: 'btn btn-sm btn-danger', "data-confirm" => "本当に削しますか?" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if user_signed_in? %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to homes_about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
               <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
          </ul>
        <% end %>
        </div>
          </div>
        </nav>
    </header>
    <main class="mb-auto">
      <div class="text-success">
        <p id="notice"><%= notice %></p>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div class="text-danger">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= @user.errors.count %>errors prohibited this obj from being saved:
          </h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      </div>
        <%= form_with model: @user, local: true do |f| %>
          <div class="form-group">
           <label for="input Name">Name</label><br>
           <%= f.text_field :name, autofocus: true, id:"inputName", class:'form-control name' %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label><br>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label><br>
            <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class: 'form-control introduction' %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class:'btn btn-secondary' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book', book: @book, user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= image_tag user.get_profile_image(40, 40)%></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/book', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(40, 40)%>
                <% end %>
              </td>
              <td><%= link_to  book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>